import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import NavigationBar from '@/components/layout/Header/NavigationBar';
import Footer from '@/components/layout/Footer/Footer';

const newYork = localFont({
  src: './fonts/NewYork.otf',
  variable: '--font-new-york',
  display: 'swap',
});

// const axiformaThin = localFont({
//   src: './fonts/Axiforma-Thin.otf',
//   variable: '--font-axiforma-thin',
//   display: 'swap',
// });

const axiformaLight = localFont({
  src: './fonts/Axiforma-Light.woff2',
  variable: '--font-axiforma-thin',
  display: 'swap',
});

const axiformaMedium = localFont({
  src: './fonts/Axiforma-Medium.woff2',
  variable: '--font-axiforma-normal',
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <body
        className={`${newYork.variable} ${axiformaLight.variable} ${axiformaMedium.variable} antialiased`}
      >
        <div className="min-h-[100dvh] grid grid-rows-[auto_1fr_auto] grid-cols-[minmax(0,1fr)]">
          <header>
            <NavigationBar />
          </header>
          <main>{children}</main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
